name: rpi-build

on:
  push:
    branches:
      - "arknight_repl"
  
  pull_request:
    branches:
      - "arknight_repl"

jobs:
  update_and_restart:
    runs-on: [self-hosted]

    steps:
      - name: Stop servers
        run: |
          systemctl --user stop chess3-web
          systemctl --user stop chess3-engine

      - name: Check out repository
        uses: actions/checkout@v3
      
      - name: (Re)start servers
        run: |
          systemctl --user start chess3-engine
          systemctl --user start chess3-web