name: rpi-build

on:
  push:
    branches:
      - "arknight_repl"
  
  pull_request:
    branches:
      - "arknight_repl"

jobs:
  update_and_restart:
    runs-on: [self-hosted]

    steps:
      - uses: actions/checkout@v3
